config/routes.rb
QuestionIt::Application.routes.draw do

  get "notifications/index"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :tags, only: [:create, :destroy, :show]
  resources :notifications, only: :index

  root to: 'static_pages#home' 
  
  match '/signup', to: 'users#new'
  match '/myquestions', to: 'users#myquestions'
  match '/allusers', to: 'users#index'
  match '/newpassword', to: 'users#new_password'
  match '/changepassword', to: 'users#create_password', via: :post
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signin', to: 'sessions#new'
  match '/newquestion', to: 'questions#new'
  match '/allquestions', to: 'questions#index'
  match '/unanswered', to: 'questions#unanswered'
  match '/tags', to: 'tags#index'
  match '/voteplus', to: 'answers#vote_plus', via: :put
  match '/voteminus', to: 'answers#vote_minus', via: :put
  match '/bestanswer', to: 'answers#best_answer', via: :put
  match '/erasenotification', to: 'notifications#erase_notification', via: :put
 

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
 

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  country         :string(255)
#  city            :string(255)
#  birthdate       :date
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
	attr_accessible :email, :name, :password , :password_confirmation, :country, :city, :birthdate
  attr_accessor :setting_password
	has_secure_password
	has_many :questions, dependent: :destroy
	has_many :answers, dependent: :destroy
	has_many :comments, dependent: :destroy
  has_and_belongs_to_many :voted_answers, class_name: 'Answer'
  has_many :received_notifications, dependent: :destroy, :class_name => 'Notification', :foreign_key => 'reported_user_id'
  has_many :issued_notifications, dependent: :destroy, :class_name => 'Notification', :foreign_key => 'issuer_user_id'
	
	before_save do |user|
		user.name = user.name.downcase.gsub(/\s+/, ' ').split(' ').map(&:capitalize).join(' ')
		email.downcase!
		user.country = user.country.downcase.gsub(/\s+/, ' ').split(' ').map(&:capitalize).join(' ')
		user.city = user.city.downcase.gsub(/\s+/, ' ').split(' ').map(&:capitalize).join(' ')
	end
	
	before_save :create_remember_token
	
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
	
	validates :password, length: { minimum: 6 }, if: :setting_password 
	validates :password_confirmation, presence: true, if: :setting_password 
	
	validates :country, presence: true, length: { maximum: 50 }
	validates :city, presence: true, length: { maximum: 50 }
	validates :birthdate, presence: true
	
	private
	
		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:edit, :update, :destroy, :myquestions]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy
  before_filter :signed_out_user, only: [:new, :create, :new_password, :create_password]
  before_filter :not_admin_user , only: :myquestions

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.setting_password = true
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Question It!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    @user.attributes = params[:user]
    @user.setting_password = false
    if !@user.password.empty? || !@user.password_confirmation.empty?
      @user.setting_password = true
    end
    if @user.save
      if current_user?(@user) 
        flash[:success] = "Your information was updated!"
        sign_in @user
      else
        flash[:success] = "Updated!"
      end
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    unless current_user?(@user)
      name_user_destroyed = @user.name
      @user.destroy
      flash[:success] = "#{name_user_destroyed} destroyed"
      redirect_to allusers_path
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def myquestions
    @questions = current_user.questions.paginate(page: params[:page])
  end

  def new_password
    @user = User.new 
  end

  def create_password
    @user = User.find_by_email(params[:email])
    password = (0...8).map{(65+rand(26)).chr}.join 
    if @user.nil?
      flash.now[:failure] = "E-mail does not belong to Question It community"
      render 'new_password'
    else
      @user.password = password
      @user.password_confirmation = password
      @user.save
      UserMailer.recover_password_email(@user, password).deliver
      flash[:success] = "New password sent to e-mail"
      redirect_to signin_path
    end
  end

  private

  def signed_out_user
    redirect_to root_url unless !signed_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user) || current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper

# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  def calculate_age(user_birthdate)
	(Date.today - user_birthdate).to_i/365  
  end
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<%= f.label :name %>
<%= f.text_field :name %>
			
<%= f.label :email %>
<%= f.text_field :email %>

<% if edit %>
  <%= link_to "change password", 'javascript:;', id: "change_password_btn" %>
<% end %>

<div id="password_fields" <% if edit %><%= 'style=display:none;' %><% end %>>
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>
</div>

<%= f.label :city %>
<%= f.text_field :city %>
			
<%= f.label :country %>
<%= f.text_field :country %>
	
<%= f.label :birthdate %>
<%= f.date_select(:birthdate, start_year: 1930, end_year: 2011, order: [:day, :month, :year]) %>
			

app/views/users/_user.html.erb
<% if !user.admin? %> 
	<li>
		<%= gravatar_for user, size: 52 %>
		<%= link_to user.name, user %>
		<span class="edit_delete_btn">
			<% if !current_user.nil? && current_user.admin? && !current_user?(user) %>
				<%= link_to "Edit", edit_user_path(user), class: "btn btn-warning btn-small"%>
				<%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure?" }, 
				class: "btn btn-danger btn-small"%>
			<% end %>
		</span>
	</li>
<% end %>

app/views/users/edit.html.erb
<% provide(:title,'Edit User') %>
<% if current_user?(@user) %>
	<h1>Edit Your Profile</h1>
<% else %>
	<h1>Edit User</h1>
<% end %>

<div class= "row" >
	<div class= "span6 offset3">
		<%= gravatar_for @user %>
		<%= link_to "Change your picture", "http://gravatar.com/emails", target: "_blank" %>
		<br></br><br></br>
		<%= form_for(@user) do |f| %>
			<%= render 'users/fields', f: f, edit: true %>
			<%= f.submit "Save changes", disable_with: "Saving...", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1>Users</h1>

<%= will_paginate @users %>

<% if @users.any? %>
  <ul class="users">
    <%= render @users %>
  </ul>
<% else %>
  <h5>No users...</h5>
<% end %>

<%= will_paginate @users %>

app/views/users/myquestions.html.erb
<% provide(:title, 'My Questions') %>
<h1>My Questions</h1>

<%= render 'shared/questions' %>

app/views/users/new.html.erb
<% provide(:title,'Sign Up') %>
<h1>Sign Up</h1>

<div class= "row" >
	<div class= "span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'users/fields', f: f, edit: false %>
			<%= f.submit "Create my account", disable_with: "Creating...", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/new_password.html.erb
<% provide(:title, 'Reset Password') %>
<h1>Reset Password</h1>

<div class="container">
  <div class="row">
    <div class="span6 offset3">
      <%= form_tag(changepassword_path, method: "post") do %>
        <%= label_tag :email, "Your email" %>
        <%= text_field_tag :email %>
        <%= submit_tag "Send password!", disable_with: "Sending...", class: "btn btn-large btn-primary" %>
      <% end %>    
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<aside class="span12">
		<section>
			<h2>
				<%= @user.name %>
			</h2>
		</section>
	</aside>
</div>
<div class="left hero-unit">
	<%= gravatar_for @user, size: 150 %>
	<ul id="profile_info">
		<li>E-mail: <%= @user.email %> </li>
		<li>Location: <%= "#{@user.city} , #{@user.country}" %> </li>
		<li>Age: <%= calculate_age(@user.birthdate) %> </li>
	</ul>
</div>