config/routes.rb
QuestionIt::Application.routes.draw do

  get "notifications/index"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :tags, only: [:create, :destroy, :show]
  resources :notifications, only: :index

  root to: 'static_pages#home' 
  
  match '/signup', to: 'users#new'
  match '/myquestions', to: 'users#myquestions'
  match '/allusers', to: 'users#index'
  match '/newpassword', to: 'users#new_password'
  match '/changepassword', to: 'users#create_password', via: :post
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signin', to: 'sessions#new'
  match '/newquestion', to: 'questions#new'
  match '/allquestions', to: 'questions#index'
  match '/unanswered', to: 'questions#unanswered'
  match '/tags', to: 'tags#index'
  match '/voteplus', to: 'answers#vote_plus', via: :put
  match '/voteminus', to: 'answers#vote_minus', via: :put
  match '/bestanswer', to: 'answers#best_answer', via: :put
  match '/erasenotification', to: 'notifications#erase_notification', via: :put
 

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
 

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_question_item.html.erb
<li class="question_item">
  <span class="edit_delete_btn">
      <% if current_path?(myquestions_path) %>
        <%= link_to "Edit", edit_question_path(question_item), class: "btn btn-warning btn-small"%>
      <% end %>
      <% if !current_user.nil? && current_user.admin? %>
        <%= link_to "Edit", edit_question_path(question_item), class: "btn btn-warning btn-small"%>
        <%= link_to "Delete", question_item, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger btn-small"%>
      <% end %>
  </span>
  <span class="question_item_title"><h4><%= link_to question_item.title, question_item %></h4></span>
  <span class="question_item_content"><%= clean_and_shorten(question_item.content) %></span>
  <% if !current_path?(myquestions_path) %>
	<% if current_user?(question_item.user) %>
		<span class="question_item_autor">Asked by <%= link_to "me", question_item.user %></span>
	<% else %>
		<span class="question_item_autor">Asked by <%= link_to question_item.user.name, question_item.user %></span>
	<% end %>
  <% end %>
  <span class="question_item_info">
    <%= pluralize(question_item.answers.count, 'answer') %> / Asked <%= time_ago_in_words(question_item.created_at) %> ago.
  </span>
</li>

app/views/shared/_questions.html.erb
<% if @questions.any? %>
  <%= will_paginate @questions %>
  <ul class="questions">
    <%= render partial: 'shared/question_item', collection: @questions %>
  </ul>
  <%= will_paginate @questions %>
<% else %>
  <h5>No questions...</h5>
<% end %>