config/routes.rb
QuestionIt::Application.routes.draw do

  get "notifications/index"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :tags, only: [:create, :destroy, :show]
  resources :notifications, only: :index

  root to: 'static_pages#home' 
  
  match '/signup', to: 'users#new'
  match '/myquestions', to: 'users#myquestions'
  match '/allusers', to: 'users#index'
  match '/newpassword', to: 'users#new_password'
  match '/changepassword', to: 'users#create_password', via: :post
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signin', to: 'sessions#new'
  match '/newquestion', to: 'questions#new'
  match '/allquestions', to: 'questions#index'
  match '/unanswered', to: 'questions#unanswered'
  match '/tags', to: 'tags#index'
  match '/voteplus', to: 'answers#vote_plus', via: :put
  match '/voteminus', to: 'answers#vote_minus', via: :put
  match '/bestanswer', to: 'answers#best_answer', via: :put
  match '/erasenotification', to: 'notifications#erase_notification', via: :put
 

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
 

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  content     :text
#  user_id     :integer
#  question_id :integer
#  vote        :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  best_answer :boolean          default(FALSE)
#

class Answer < ActiveRecord::Base
  attr_accessible :content, :vote, :best_answer
  belongs_to :user
  belongs_to :question
  has_many :comments, dependent: :destroy, :as => :commentable
  has_and_belongs_to_many :voting_users, class_name: 'User'

  before_save :default_values

  validates :user_id, presence: true
  validates :question_id, presence: true
  validates :content, presence: true

  default_scope order: 'answers.vote DESC'

  private

  def default_values
    self.vote ||= 0
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_filter :signed_in_user
  before_filter :not_admin_user

  def create
    @answer = current_user.answers.build(params[:answer])
    @answer.question = Question.find(params[:question_id])
    if @answer.save
      if !current_user?(@answer.question.user)
        send_notification(@answer)
      end
      flash[:success] = "Answer posted!"
    else
      flash[:failure] = "Please write the answer"
    end


    redirect_to @answer.question
  end

  def vote_plus
    @answer = Answer.find(params[:id])
    if !@answer.voting_users.include?(current_user)
      @answer.vote = @answer.vote + 1
      @answer.save
      @answer.voting_users << current_user
      if !current_user?(@answer.user)
        send_voteup_notification(@answer)
      end
      if !current_user?(@answer.question.user)
        notify_voteup_questioner(@answer)
      end
      flash[:success] = "Positive vote posted!"
    else
      flash[:failure] = "You've already voted for that answer"
    end

    redirect_to @answer.question
  end

  def vote_minus
    @answer = Answer.find(params[:id])
    if !@answer.voting_users.include?(current_user)
      @answer.vote = @answer.vote - 1
      @answer.save
      @answer.voting_users << current_user
      if !current_user?(@answer.user)
        send_votedown_notification(@answer)
      end
      if !current_user?(@answer.question.user)
        notify_votedown_questioner(@answer)
      end
      flash[:success] = "Negative vote posted!"
    else
      flash[:failure] = "You've already voted for that answer"
    end

    redirect_to @answer.question
  end

  def best_answer
    @answer = Answer.find(params[:id])
    @answer.question.answers.each do |answer|
      if answer.best_answer
        answer.best_answer = false
        answer.save
      end	
    end
    @answer.best_answer = true
    @answer.save

    send_bestanswer_notification(@answer)

    redirect_to @answer.question
  end

  private

  def send_notification(answer)
    reported_user = answer.question.user
    @notification = Notification.new
    @notification.reported_user = reported_user
    @notification.issuer_user = current_user
    @notification.question = answer.question
    @notification.title = "Question answered!"
    @notification.description = "A question posted by you has been answered"
    @notification.save
  end

  def send_voteup_notification(answer)
    reported_user = answer.user
    @notification = Notification.new
    @notification.reported_user = reported_user
    @notification.issuer_user = current_user
    @notification.question = answer.question
    @notification.title = "Answer voted up!"
    @notification.description = "An answer posted by you has been voted up"
    @notification.save
  end

  def send_votedown_notification(answer)
    reported_user = answer.user
    @notification = Notification.new
    @notification.reported_user = reported_user
    @notification.issuer_user = current_user
    @notification.question = answer.question
    @notification.title = "Answer voted down!"
    @notification.description = "An answer posted by you has been voted down"
    @notification.save
  end

  def notify_voteup_questioner(answer)
    reported_user = answer.question.user
    @notification = Notification.new
    @notification.reported_user = reported_user
    @notification.issuer_user = current_user
    @notification.question = answer.question
    @notification.title = "Question's answer voted up!"
    @notification.description = "An answer of a question posted by you has been voted up"
    @notification.save
  end

  def notify_votedown_questioner(answer)
    reported_user = answer.question.user
    @notification = Notification.new
    @notification.reported_user = reported_user
    @notification.issuer_user = current_user
    @notification.question = answer.question
    @notification.title = "Question's answer voted down!"
    @notification.description = "An answer of a question posted by you has been voted down"
    @notification.save
  end

  def send_bestanswer_notification(answer)
    reported_user = answer.user
    @notification = Notification.new
    @notification.reported_user = reported_user
    @notification.issuer_user = current_user
    @notification.question = answer.question
    @notification.title = "Answer selected as best answer!"
    @notification.description = "Your answer for a question has been selected as the best answer"
    @notification.save
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<li>

  <div class="row">
    <div class="span2">
      <%= render 'answers/answer_votes', answer: answer %>
      <% if answer.best_answer? %>
        <p class="best_answer">
        <%= image_tag "checkmark.png", height: "15", width: "15" %>
        best answer
        </p>
      <% end %>
    </div>

    <div class="span9">
      <% if current_user?(@question.user) && !answer.best_answer? %>
        <p class="add_best_answer">
			<%= link_to("select as best answer", bestanswer_path(id: answer.id), method: :put) %>
      <%= image_tag "star.png", height: "15", width: "15" %>
        </p>
      <% end %>
      <div class="hero-unit">
        <span class="answer_content">
          <%= answer.content.html_safe %>
        </span>
        <span class="answer_item_info">
          answered <%= time_ago_in_words(answer.created_at)%> ago. 
		  <% if current_user?(answer.user) %>
			By <%= link_to "me" , answer.user %>
		  <% else %>
			By <%= link_to answer.user.name , answer.user %>
		  <% end %>
        </span>
        <div class="hidden_answer_comment">
          <%= render 'comments/comment_form', commentable_id: answer.id, commentable: 'answer' %>
        </div>
      </div>
    </div> 
  </div>

  <div class="row">
    <div class="span3 offset8">
      <%if signed_in?	%>
        <% if !current_user.admin? %>
          <p class="comment_text_answer">
          <%= link_to("comment", 'javascript:;', class: 'answer_comment_btn') %>
          </p>
        <% end %>
      <% else %>
        <p class="comment_text_answer">
        <%= link_to("Log in", signin_path) %> to comment it!
        </p>
      <% end %>
    </div>
  </div>

  <div class="row"> 
    <div class="span9 offset2">
      <%= render 'comments/all_comments' , commentable: answer %>
    </div>
  </div>

  </li>

app/views/answers/_answer_form.html.erb
<hr class="separation_line"></hr>
<div class="row">
	<div class="span12">
		<h3>Your Answer</h3>
        <%= form_for(@answer) do |f| %>
          <%= f.cktext_area :content, rows: "7", class: "html_editor" %>
          <%= hidden_field_tag :question_id, params[:id] %>
          <%= f.submit "Answer it!", disable_with: "Posting...",  class: "btn btn-large btn-primary html_editor_submit_btn" %>
        <% end %>
    </div>
</div>

app/views/answers/_answer_votes.html.erb
<div class="center vote_counter">
  <h2><%= answer.vote %></h2>
</div>
<div class="center">
  <% if signed_in? %>
    <% if !current_user.admin? %>
      <%= link_to(image_tag("minus.png"), voteminus_path(id: answer.id), method: :put, class: 'vote_button' ) %>
      <%= link_to(image_tag("plus.png"), voteplus_path(id: answer.id), method: :put, class: 'vote_button') %>
      <%= image_tag "voting.gif", class: 'voting_gif' %>
    <% end %>
  <% else %>
    <p class="vote_text"><%= link_to "Log in", signin_path %> to vote it!</p>
  <% end %>
</div>