config/routes.rb
QuestionIt::Application.routes.draw do

  get "notifications/index"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :tags, only: [:create, :destroy, :show]
  resources :notifications, only: :index

  root to: 'static_pages#home' 
  
  match '/signup', to: 'users#new'
  match '/myquestions', to: 'users#myquestions'
  match '/allusers', to: 'users#index'
  match '/newpassword', to: 'users#new_password'
  match '/changepassword', to: 'users#create_password', via: :post
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signin', to: 'sessions#new'
  match '/newquestion', to: 'questions#new'
  match '/allquestions', to: 'questions#index'
  match '/unanswered', to: 'questions#unanswered'
  match '/tags', to: 'tags#index'
  match '/voteplus', to: 'answers#vote_plus', via: :put
  match '/voteminus', to: 'answers#vote_minus', via: :put
  match '/bestanswer', to: 'answers#best_answer', via: :put
  match '/erasenotification', to: 'notifications#erase_notification', via: :put
 

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
 

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
	  <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
  <div class="container">
    <%= link_to "Question It", root_path, id: "logo" %>
    <%= link_to "!", root_path, id: "logo_exclamation" %>
    <nav>
    <ul class="nav pull-right">
      <% if !signed_in? %>
        <li><%= link_to "Sign up", signup_path %></li>
        <li><%= link_to "Log in", signin_path %></li>
      <% else %>
        <li><%= link_to "#{current_user.name}", current_user %></li>
        <li id="fat-menu" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account
          <% if current_user.received_notifications.any? %>
            <sup>
              <span class="badge badge-important">
                <%= current_user.received_notifications.count %>
              </span>
            </sup>
          <% end %>
          <b class="caret"></b> 
        </a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Edit", edit_user_path(current_user) %></li>
          <% if !current_user.admin? %>
            <li>
            <a href="<%= notifications_path %>">Notifications
              <% if current_user.received_notifications.any? %>
                  <span class="badge badge-important">
                    <%= current_user.received_notifications.count %>
                  </span>
              <% end %>
            </a>
            </li>
            <li><%= link_to "My Questions", myquestions_path %></li>
          <% end %>
          <li class="divider"></li>
          <li>
          <%= link_to "Log out", signout_path, method: "delete" %>
          </li>
        </ul>
        </li>
      <% end %>		
    </ul>
    </nav>
  </div>
</div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/_subheader.html.erb
<% if !current_path?(root_path) %>
	<div class="container">
	  <ul class="nav nav-pills pull-right" id="subheader">
		<li <%= 'class=active' if current_path?(allquestions_path) %>>
		<%= link_to 'Questions', allquestions_path %>
		</li>
		<li <%= 'class=active' if current_path?(allusers_path) %>>
		<%= link_to 'Users', allusers_path %> 
		</li>
		<li <%= 'class=active' if current_path?(tags_path) %>>
		<%= link_to 'Tags', tags_path %> 
		</li>
		<li <%= 'class=active' if current_path?(unanswered_path) %>>
		<%= link_to 'Unanswered', unanswered_path %> 
		</li>
		<% if !current_user.nil? && !current_user.admin? %>
		  <li <%= 'class=active' if current_path?(newquestion_path) %>>
		  <%= link_to 'Ask Question', newquestion_path %> 
		  </li>
		<% end %>
	  </ul>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  
</head>
<body>
	<%= render 'layouts/header' %>
	<% if !current_path?(signup_path) && !current_path?(signin_path) && !current_path?(users_path) && !current_path?(sessions_path) %>
		<%= render 'layouts/subheader' %>
	<% end %>
	<div class= "container" >
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %> </div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>